[package]
name = "gitlab_connector"
version = "0.1.0"
authors = ["Ben Lipton <ben.lipton@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.9"
failure = "0.1"
