[package]
name = "gitlab_connector"
version = "0.1.0"
authors = ["Ben Lipton <ben@grimm-co.com>"]

[dependencies]
hyper = "0.12"
futures = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.8"
failure = "0.1"
